server.port: 9001
spring:
  application:
    name: user-store-service

eureka:
  instance:
    prefer-ip-address: true   # 호스트명 대신 IP로 등록
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/