version: '3.8'

services:
  auth:
    image: quay.io/bread0930/chord-server-auth:latest
    container_name: auth
    network_mode: "host"
    ports:
      - "9000:9000"
    env_file:
      - common.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  user-store:
    image: quay.io/bread0930/chord-server-user-store:latest
    container_name: user-store
    network_mode: "host"
    ports:
      - "9001:9001"
    env_file:
      - common.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

networks:
  coachcoach-network:
    driver: bridge
