version: '3.8'

services:
  catalog:
    image: quay.io/bread0930/chord-server-catalog:latest
    container_name: catalog
    network_mode: "host"
    ports:
      - "9002:9002"
    env_file:
      - common.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  insight:
    image: quay.io/bread0930/chord-server-insight:latest
    container_name: insight
    network_mode: "host"
    ports:
      - "9003:9003"
    env_file:
      - common.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

networks:
  coachcoach-network:
    driver: bridge
