version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - coachcoach-network
    restart: unless-stopped

  gateway:
    image: quay.io/bread0930/chord-server-gateway:latest
    container_name: gateway
    ports:
      - "8080:8000"
    env_file:
      - common.env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx128m -Xms64m
    networks:
      - coachcoach-network
    restart: unless-stopped

networks:
  coachcoach-network:
    name: compose_coachcoach-network
    external: true