server.port: 9002
spring:
  application:
    name: catalog-service

eureka:
  instance:
    prefer-ip-address: true   # 호스트명 대신 IP로 등록
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.0.0.107:8761/eureka/