spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
app:
  datasource:
    catalog:
      url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${CATALOG_DB_NAME}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    user:
      url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${USER_DB_NAME}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    insight:
      url: jdbc:postgresql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${INSIGHT_DB_NAME}
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

logging:
  level:
    com.coachcoach: INFO  # 프로젝트 로그 레벨
    org.hibernate.SQL: INFO  # SQL 로그
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # 바인딩 파라미터
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    org.springframework.web.servlet.resource: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
